### Importing PyTorch

In [1]:
import torch
torch.__version__

'2.2.2+cpu'

# Introduction to tensors

Tensors are the fundamental buidling block of machine learning.
Their job is to represent data in a numerical way.

EX: A tensor with shape [3, 224, 224] can be [color_channels, height, width], as in the image has 3 color channels(RGB), a height of 224 pixels and a width of 224 pixels.

### Creating tensors in PyTorch

In [2]:
# Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

Chek the dimensions of a tensor using the ndim attribute

In [3]:
scalar.ndim

0

Retrieve the number from the tensor using the item() method

In [4]:
scalar.item()

7

In [5]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.


In [7]:
vector.shape

torch.Size([2])

This is because of the two elements we placed inside the square brackets([7, 7]).

In [8]:
# Matrix
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random tensors
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [14]:
random_tensor=torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0582, 0.9371, 0.3672, 0.6569],
         [0.2204, 0.1921, 0.8432, 0.8850],
         [0.2315, 0.3196, 0.1026, 0.9369]]),
 torch.float32)

In [15]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# torch.zeros and torch.ones

In [16]:
zeros=torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones=torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range and tensors like
You can use torch.arange(start, end, step) to do so.

Note: In Python, you can use range() to create a range, by in PyTorch, torch.range() is deprecated and may show an error.future.

In [18]:
zero_to_ten_deprecated=torch.range(0,10)

zero_to_ten=torch.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\user\AppData\Local\Temp\ipykernel_17836\709803459.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated=torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To do so, you can use 
torch.zeros_like(input)
or
torch.ones_like(input)

In [19]:
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
ten_ones=torch.ones_like(input=ten_zeros)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes

Lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluations metrics like accuracy.

In [21]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors
shape, dtype, device are the most common attributes.

In [23]:
some_tensor=torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.4791, 0.7172, 0.0697, 0.3434],
        [0.0581, 0.6294, 0.7597, 0.2216],
        [0.3723, 0.7616, 0.9845, 0.5932]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor operations

Addition, Subtraction, Multiplication, Division, Matrix multiplication

In [24]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [25]:
tensor*10

tensor([10, 20, 30])

In [26]:
tensor

tensor([1, 2, 3])

In [27]:
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [28]:
tensor=tensor+10
tensor

tensor([1, 2, 3])

In [29]:
# Element-wise muliplication
print(tensor,"*",tensor)
print("Equals to",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals to tensor([1, 4, 9])


### Matrix multiplication( is all you need!)
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [30]:
import torch
tensor=torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [31]:
print(tensor*tensor)
print(tensor@tensor) # Not recommended
print(torch.matmul(tensor,tensor))

tensor([1, 4, 9])
tensor(14)
tensor(14)


In [32]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 2.17 ms


tensor(14)

In [33]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

#### One of the most common errors in deep learning (shape erros)

In [34]:
A=torch.tensor([[1,2],
               [3,4],
               [5,6]], dtype=torch.float32)
B=torch.tensor([[7,10],
               [8,11],
               [9,12]], dtype=torch.float32)
torch.matmul(A,B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
# Transposing
print(A)
print(B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [36]:
print(f"Original shapes: A={A.shape}, B={B.shape}\n")
print(f"New shapes: A={A.shape} (same), B={B.T.shape}\n")
print(f"Multiplying: {A.shape}*{B.T.shape} <- the inner dimensions match!\n")
print("Output:\n")
output=torch.matmul(A,B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: A=torch.Size([3, 2]), B=torch.Size([3, 2])

New shapes: A=torch.Size([3, 2]) (same), B=torch.Size([2, 3])

Multiplying: torch.Size([3, 2])*torch.Size([2, 3]) <- the inner dimensions match!

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [37]:
# torch.mm is a shortcut for matmul
torch.mm(A,B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

The torch.nn.Linear() module is fully connected layer of PyTorch.

In [40]:
torch.manual_seed(42)

linear=torch.nn.Linear(in_features=2,
                       out_features=6)

x=A
output=linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output: \n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#### Remember, matrix multiplication is all you need.

# Aggregation

In [43]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")

print(f"Mean: {x.type(torch.float32).mean()}") # Must be the float32 datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

In [46]:
tensor=torch.arange(10,100,10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Change tensor datatype

In [47]:
tensor=torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [48]:
tensor_float16=tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [49]:
tensor_int8=tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqeezing

To do so, some popular methods are:

torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [50]:
import torch
x=torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
# Add an extra dimension
x_reshaped=x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Change view: keeps same data as original but changes view
z=x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

So changing the view changes the original tensor too.

In [53]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [58]:
# Stack tensors on top of each other
x_stacked_first_dim=torch.stack([x,x,x,x], dim=0)
x_stacked_second_dim=torch.stack([x,x,x,x], dim=1)
x_stacked_first_dim, x_stacked_second_dim

(tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]))

#### Squeezing tensor means make a vecotr from a tensor

In [59]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [64]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0) # Row-wise unsqueezing
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [65]:
x_original=torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis order
x_permuted=x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors

In [74]:
import torch
x=torch.arange(1,10).reshape(1,3,3) # Num of matrices, num of vectors, num of scalars
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

### Indexing values goes outer dimension to inner dimension

In [67]:
print(f"First square bracket: \n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [69]:
x[:,0], x[:,:,1], x[:,1,1], x[0,0,:] # Scalar(0), Vector(1), Matrix(2),...

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]), tensor([5]), tensor([1, 2, 3]))

# PyTorch tensors & NumPy

torch.from_numpy(ndarray) : NumPy array to PyTorch tensor.<br>
torch.Tensor.numpy() : PyTorch tensor to NumPy array

In [75]:
import torch;import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

***
> Note: By default, NumPy arrays are created with the datatype torch.float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype(as above).
> However, many PyTorch caculations default to using torch.float32.
> So if you want to convert your NumPy array to PyTorch tensor with torch.float32 datatype, you can use tensor=torch.fram_numpy(array).type(torch.float(32).

In [76]:
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [386]:
tensor+=1
tensor, numpy_tensor

(tensor([306., 306., 306., 306., 306., 306., 306.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (reliable randomized result)

In [388]:
import torch

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print("Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A==random_tensor_B

Tensor A:
tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])

Tensor B:
tensor([[0.7891, 0.1694, 0.1800, 0.7177],
        [0.6988, 0.5510, 0.2485, 0.8518],
        [0.0963, 0.1338, 0.2741, 0.6142]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [389]:
import torch
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print("Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C==random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPU

In [396]:
!!nvidia-smi # Checking NVIDIA GPU is available

["'nvidia-smi'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는", '배치 파일이 아닙니다.']

In [398]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [433]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [434]:
# Count number of devices
torch.cuda.device_count()

0

# Moving tensors back to the CPU
All codes are just examples, so error code now.

In [435]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

NameError: name 'tensor_on_gpu' is not defined

In [436]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

NameError: name 'tensor_on_gpu' is not defined